version: '3.7'
services:
    postgres:
        image: postgres:14.2-alpine
        container_name: epg
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
            # The official postgres image has a script /usr/local/bin/docker-entrypoint.sh
            # which executes each each *.sh, **.sql and *.*sql.gz in /docker-entrypoint-initdb.d/ at startup
            - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
            - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql